'use client';

import { PointerEvent, useCallback, useEffect, useRef, useState } from 'react';

type Scenario = 'deform' | 'ghost' | 'boost' | 'slingshot' | 'respawn' | 'draw';
type Point = { x: number; y: number };
type MockTool = 'select' | 'draw' | 'carA' | 'carB' | 'wall' | 'pylon1' | 'pylon2';
type MockSelection = 'carA' | 'carB' | 'wall' | 'pylon1' | 'pylon2' | null;
type MockCar = { point: Point; angle: number };
type Mockup = { seeded: boolean; drawing: boolean; track: Point[]; carA?: MockCar; carB?: MockCar; wall?: { point: Point; angle: number }; pylon1?: Point; pylon2?: Point; drag?: MockSelection };
const entries: { id: Scenario; label: string; detail: string }[] = [
  { id: 'draw', label: '00 · Tracer à deux', detail: 'Deux demi-tracés ferment le circuit.' },
  { id: 'deform', label: '01 · Déformer la piste', detail: 'Le circuit se décale autour du mur.' },
  { id: 'ghost', label: '02 · Passer en fantôme', detail: 'Le pilote traverse le mur.' },
  { id: 'boost', label: '03 · Dessiner un boost', detail: 'Trois doigts créent une zone accélérante.' },
  { id: 'slingshot', label: '04 · Lance-pierre', detail: 'Deux appuis et un drag tirent un projectile.' },
  { id: 'respawn', label: '05 · Sortie et respawn', detail: 'Le mur éjecte la voiture hors piste.' },
];
const clamp = (v: number, a: number, b: number) => Math.max(a, Math.min(b, v));
const lerp = (a: number, b: number, t: number) => a + (b - a) * t;

export default function Home() {
  const canvas = useRef<HTMLCanvasElement>(null); const frame = useRef(0); const begun = useRef(performance.now()); const pauseAt = useRef<number | null>(null); const paused = useRef(0); const live = useRef(true);
  const screenshotRef = useRef(false); const mockLabRef = useRef(false); const selectedMockRef = useRef<MockSelection>(null); const mockRef = useRef<Mockup>({ seeded: false, drawing: false, track: [] });
  const [scenario, setScenario] = useState<Scenario>('deform'); const [running, setRunning] = useState(true); const [phase, setPhase] = useState('Coéquipier : saisie de la bordure'); const [hp, setHp] = useState(100); const [screenshot, setScreenshot] = useState(false); const [mockLab, setMockLab] = useState(false); const [mockTool, setMockTool] = useState<MockTool>('select'); const [selectedMock, setSelectedMock] = useState<MockSelection>(null);
  const restart = useCallback((id: Scenario) => { begun.current = performance.now(); pauseAt.current = null; paused.current = 0; live.current = true; setRunning(true); setScenario(id); setHp(100); }, []);
  const toggle = () => { const now = performance.now(); if (live.current) { pauseAt.current = now; live.current = false; setRunning(false); } else { paused.current += now - (pauseAt.current ?? now); pauseAt.current = null; live.current = true; setRunning(true); } };
  const openMock = () => { mockRef.current = { seeded: false, drawing: false, track: [] }; mockLabRef.current = true; setMockLab(true); setMockTool('select'); };
  const showScreenshot = () => { screenshotRef.current = true; setScreenshot(true); };
  const closeMock = () => { screenshotRef.current = false; setScreenshot(false); };
  const mockPoint = (event: PointerEvent<HTMLCanvasElement>) => { const box = event.currentTarget.getBoundingClientRect(); return { x: event.clientX - box.left, y: event.clientY - box.top }; };
  const selectMock = (next: MockSelection) => { selectedMockRef.current = next; setSelectedMock(next); };
  const mockDown = (event: PointerEvent<HTMLCanvasElement>) => { if (!mockLabRef.current) return; const p = mockPoint(event); const mock = mockRef.current; const near = (value: Point | undefined) => value && Math.hypot(value.x - p.x, value.y - p.y) < 28; if (mockTool === 'select') { const hit: MockSelection = near(mock.carA?.point) ? 'carA' : near(mock.carB?.point) ? 'carB' : near(mock.wall?.point) ? 'wall' : near(mock.pylon1) ? 'pylon1' : near(mock.pylon2) ? 'pylon2' : null; selectMock(hit); mock.drag = hit; } else if (mockTool === 'draw') { mock.track = [p]; mock.drawing = true; } else if (mockTool === 'carA') { mock.carA = { point: p, angle: 0 }; selectMock('carA'); } else if (mockTool === 'carB') { mock.carB = { point: p, angle: 0 }; selectMock('carB'); } else if (mockTool === 'wall') { mock.wall = { point: p, angle: mock.wall?.angle ?? 0 }; selectMock('wall'); } else if (mockTool === 'pylon1') { mock.pylon1 = p; selectMock('pylon1'); } else if (mockTool === 'pylon2') { mock.pylon2 = p; selectMock('pylon2'); } event.currentTarget.setPointerCapture(event.pointerId); };
  const mockMove = (event: PointerEvent<HTMLCanvasElement>) => { const mock = mockRef.current; if (!mockLabRef.current || !event.buttons) return; const p = mockPoint(event); if (mock.drawing) { const last = mock.track.at(-1); if (!last || Math.hypot(last.x - p.x, last.y - p.y) > 6) mock.track.push(p); } const target = mock.drag; if (target === 'carA' && mock.carA) mock.carA.point = p; if (target === 'carB' && mock.carB) mock.carB.point = p; if (target === 'wall' && mock.wall) mock.wall.point = p; if (target === 'pylon1') mock.pylon1 = p; if (target === 'pylon2') mock.pylon2 = p; };
  const mockUp = () => { if (mockLabRef.current) { mockRef.current.drawing = false; mockRef.current.drag = null; } };
  const touch = (ctx: CanvasRenderingContext2D, p: Point, color: string, now: number, label?: string) => { const s = 1 + Math.sin(now / 110) * .12; ctx.save(); ctx.strokeStyle = color; ctx.fillStyle = `${color}28`; ctx.shadowColor = color; ctx.shadowBlur = 20; [9, 18, 29].forEach((r) => { ctx.beginPath(); ctx.arc(p.x, p.y, r * s, 0, Math.PI * 2); ctx.stroke(); }); ctx.beginPath(); ctx.arc(p.x, p.y, 5, 0, Math.PI * 2); ctx.fill(); if (label) { ctx.shadowBlur = 0; ctx.fillStyle = '#eaf6ff'; ctx.font = '600 11px Arial'; ctx.textAlign = 'center'; ctx.fillText(label, p.x, p.y - 39); } ctx.restore(); };
  const draw = useCallback((now: number) => {
    const el = canvas.current; if (!el) return; const b = el.getBoundingClientRect(); const dpr = Math.min(devicePixelRatio || 1, 2); if (el.width !== Math.round(b.width * dpr)) { el.width = Math.round(b.width * dpr); el.height = Math.round(b.height * dpr); } const ctx = el.getContext('2d'); if (!ctx) return; const w = b.width; const h = b.height; const t = ((live.current ? now : pauseAt.current ?? now) - begun.current - paused.current) / 1000;
    ctx.setTransform(dpr, 0, 0, dpr, 0, 0); ctx.clearRect(0, 0, w, h); const bg = ctx.createRadialGradient(w * .5, h * .5, 0, w * .5, h * .5, w * .72); bg.addColorStop(0, '#16274c'); bg.addColorStop(.55, '#080d20'); bg.addColorStop(1, '#03050c'); ctx.fillStyle = bg; ctx.fillRect(0, 0, w, h); ctx.save(); ctx.strokeStyle = 'rgba(75,172,255,.10)'; for (let x = -h; x < w + h; x += 44) { ctx.beginPath(); ctx.moveTo(x, 0); ctx.lineTo(x + h * .28, h); ctx.stroke(); } for (let y = 0; y < h; y += 44) { ctx.beginPath(); ctx.moveTo(0, y); ctx.lineTo(w, y - w * .16); ctx.stroke(); } ctx.restore();
    if (screenshotRef.current || mockLabRef.current) {
      const mock = mockRef.current;
      if (!mock.seeded) { mock.seeded = true; mock.track = [{ x: w * .22, y: h * .51 }, { x: w * .17, y: h * .29 }, { x: w * .42, y: h * .17 }, { x: w * .69, y: h * .25 }, { x: w * .83, y: h * .48 }, { x: w * .74, y: h * .75 }, { x: w * .46, y: h * .83 }, { x: w * .26, y: h * .72 }]; }
      const road = (points: Point[]) => { if (points.length < 2) return; const edge = (side: number) => points.map((p, i) => { const before = points[(i - 1 + points.length) % points.length]; const after = points[(i + 1) % points.length]; const size = Math.hypot(after.x - before.x, after.y - before.y) || 1; return { x: p.x - (after.y - before.y) / size * 56 * side, y: p.y + (after.x - before.x) / size * 56 * side }; }); const drawLine = (path: Point[]) => { ctx.beginPath(); path.forEach((p, i) => i ? ctx.lineTo(p.x, p.y) : ctx.moveTo(p.x, p.y)); if (!mock.drawing) ctx.closePath(); }; ctx.save(); ctx.lineJoin = 'round'; ctx.lineCap = 'round'; ctx.shadowColor = '#22dffc'; ctx.shadowBlur = 30; ctx.strokeStyle = '#07152d'; ctx.lineWidth = 112; drawLine(points); ctx.stroke(); const left = edge(1); const right = edge(-1); ctx.shadowBlur = 16; ctx.strokeStyle = '#37dff5'; ctx.lineWidth = 4; drawLine(left); ctx.stroke(); ctx.shadowColor = '#fb5cda'; ctx.strokeStyle = '#fa58da'; drawLine(right); ctx.stroke(); ctx.setLineDash([12, 16]); ctx.shadowBlur = 0; ctx.strokeStyle = 'rgba(230,246,255,.42)'; ctx.lineWidth = 1.2; drawLine(points); ctx.stroke(); ctx.restore(); };
      road(mock.track);
      const car = (item: MockCar | undefined, color: string) => { if (!item) return; ctx.save(); ctx.translate(item.point.x, item.point.y); ctx.rotate(item.angle); ctx.shadowColor = color; ctx.shadowBlur = 18; ctx.fillStyle = color; ctx.beginPath(); ctx.moveTo(18, 0); ctx.lineTo(-9, -8); ctx.lineTo(-13, 0); ctx.lineTo(-9, 8); ctx.closePath(); ctx.fill(); ctx.restore(); };
      car(mock.carA, '#72f4ff'); car(mock.carB, '#ff76df');
      if (mock.wall) { ctx.save(); ctx.translate(mock.wall.point.x, mock.wall.point.y); ctx.rotate(mock.wall.angle); ctx.shadowColor = '#ff426d'; ctx.shadowBlur = 20; ctx.fillStyle = '#f52f62'; ctx.fillRect(-9, -53, 18, 106); ctx.fillStyle = '#ffe5ef'; ctx.fillRect(-3, -44, 6, 88); ctx.restore(); }
      const pylon = (p: Point | undefined) => { if (!p) return; ctx.save(); ctx.translate(p.x, p.y); ctx.shadowColor = '#ffe65b'; ctx.shadowBlur = 18; ctx.strokeStyle = '#ffe65b'; ctx.lineWidth = 3; ctx.beginPath(); ctx.arc(0, 0, 11, 0, Math.PI * 2); ctx.stroke(); ctx.restore(); }; pylon(mock.pylon1); pylon(mock.pylon2); if (mock.pylon1 && mock.pylon2 && Math.hypot(mock.pylon1.x - mock.pylon2.x, mock.pylon1.y - mock.pylon2.y) < 180) { ctx.save(); ctx.strokeStyle = '#ffe65b'; ctx.shadowColor = '#ffe65b'; ctx.shadowBlur = 18; ctx.lineWidth = 3; ctx.beginPath(); ctx.moveTo(mock.pylon1.x, mock.pylon1.y); ctx.lineTo(mock.pylon2.x, mock.pylon2.y); ctx.stroke(); ctx.restore(); }
      const selected = selectedMockRef.current; const selectionPoint = selected === 'carA' ? mock.carA?.point : selected === 'carB' ? mock.carB?.point : selected === 'wall' ? mock.wall?.point : selected === 'pylon1' ? mock.pylon1 : mock.pylon2; if (selectionPoint && mockLabRef.current) { ctx.save(); ctx.strokeStyle = '#fff'; ctx.setLineDash([4, 4]); ctx.strokeRect(selectionPoint.x - 23, selectionPoint.y - 23, 46, 46); ctx.restore(); }
      return;
    }
    if (scenario === 'draw') {
      const a = { x: w * .19, y: h * .56 }; const b = { x: w * .80, y: h * .51 };
      const cubic = (p0: Point, p1: Point, p2: Point, p3: Point, u: number) => { const v = 1 - u; return { x: v ** 3 * p0.x + 3 * v ** 2 * u * p1.x + 3 * v * u ** 2 * p2.x + u ** 3 * p3.x, y: v ** 3 * p0.y + 3 * v ** 2 * u * p1.y + 3 * v * u ** 2 * p2.y + u ** 3 * p3.y }; };
      const upperAt = (u: number) => u < .52 ? cubic(a, { x: w * .09, y: h * .39 }, { x: w * .25, y: h * .10 }, { x: w * .49, y: h * .19 }, u / .52) : cubic({ x: w * .49, y: h * .19 }, { x: w * .63, y: h * .28 }, { x: w * .69, y: h * .14 }, b, (u - .52) / .48);
      const lowerAt = (u: number) => u < .43 ? cubic(b, { x: w * .93, y: h * .67 }, { x: w * .73, y: h * .88 }, { x: w * .54, y: h * .81 }, u / .43) : cubic({ x: w * .54, y: h * .81 }, { x: w * .39, y: h * .73 }, { x: w * .29, y: h * .91 }, a, (u - .43) / .57);
      const samples = (fn: (u: number) => Point, amount = 1) => Array.from({ length: 74 }, (_, i) => fn(amount * i / 73));
      const base = clamp((t - 1.65) / 4.5, 0, 1); const qa = clamp(base + .1 * Math.sin(base * Math.PI * 2), 0, 1); const qb = clamp(base + .07 * Math.sin(base * Math.PI * 4), 0, 1);
      const upper = samples(upperAt); const lower = samples(lowerAt);
      const stroke = (points: Point[], color: string) => { ctx.save(); ctx.strokeStyle = color; ctx.shadowColor = color; ctx.shadowBlur = 20; ctx.lineWidth = 16; ctx.lineCap = 'round'; ctx.beginPath(); points.forEach((p, i) => i ? ctx.lineTo(p.x, p.y) : ctx.moveTo(p.x, p.y)); ctx.stroke(); ctx.shadowBlur = 0; ctx.strokeStyle = '#e8f8ff'; ctx.lineWidth = 2; ctx.stroke(); ctx.restore(); };
      if (t > 1.14 && t < 6.15) { const reveal = clamp((t - 1.14) / .54, 0, 1); ctx.save(); ctx.strokeStyle = '#dfeeff'; ctx.setLineDash([7, 6]); ctx.lineWidth = 2; ctx.beginPath(); ctx.moveTo(a.x, a.y); ctx.lineTo(lerp(a.x, b.x, reveal), lerp(a.y, b.y, reveal)); ctx.stroke(); ctx.restore(); }
      if (t < 1.05) touch(ctx, a, '#36dff5', now, 'clic A'); if (t > .72 && t < 1.52) touch(ctx, b, '#fb5cda', now, 'clic B');
      if (t >= 1.65 && t < 6.15) { stroke(samples(upperAt, qa), '#36dff5'); stroke(samples(lowerAt, qb), '#fb5cda'); if (t < 6.0) { touch(ctx, upperAt(qa), '#36dff5', now, 'équipe azur'); touch(ctx, lowerAt(qb), '#fb5cda', now, 'équipe rose'); } }
      if (t >= 6.15) { const loop = [...upper, ...lower.slice(1)]; const half = Math.min(45, h * .075); const edgeA: Point[] = []; const edgeB: Point[] = []; loop.forEach((p, i) => { const prev = loop[(i - 1 + loop.length) % loop.length]; const next = loop[(i + 1) % loop.length]; const length = Math.hypot(next.x - prev.x, next.y - prev.y) || 1; const nx = -(next.y - prev.y) / length; const ny = (next.x - prev.x) / length; edgeA.push({ x: p.x + nx * half, y: p.y + ny * half }); edgeB.push({ x: p.x - nx * half, y: p.y - ny * half }); }); const alpha = clamp((t - 6.15) / .55, 0, 1); const roulette = clamp((t - 6.3) / 2.7, 0, 1); const spin = .15 + (1 - roulette) ** 2 * 3.7; const startIndex = Math.floor((loop.length * spin) % loop.length); ctx.save(); ctx.globalAlpha = alpha; ctx.shadowColor = '#36dff5'; ctx.shadowBlur = 24; ctx.fillStyle = '#07152d'; ctx.beginPath(); [...edgeA, ...edgeB.slice().reverse()].forEach((p, i) => i ? ctx.lineTo(p.x, p.y) : ctx.moveTo(p.x, p.y)); ctx.closePath(); ctx.fill(); ctx.lineWidth = 3; ctx.strokeStyle = '#36dff5'; ctx.beginPath(); edgeA.forEach((p, i) => i ? ctx.lineTo(p.x, p.y) : ctx.moveTo(p.x, p.y)); ctx.closePath(); ctx.stroke(); ctx.strokeStyle = '#fb5cda'; ctx.beginPath(); edgeB.forEach((p, i) => i ? ctx.lineTo(p.x, p.y) : ctx.moveTo(p.x, p.y)); ctx.closePath(); ctx.stroke(); const p = loop[startIndex]; const prev = loop[(startIndex - 1 + loop.length) % loop.length]; const next = loop[(startIndex + 1) % loop.length]; const length = Math.hypot(next.x - prev.x, next.y - prev.y) || 1; const nx = -(next.y - prev.y) / length; const ny = (next.x - prev.x) / length; ctx.shadowColor = '#fff'; ctx.shadowBlur = 16; ctx.strokeStyle = '#fff'; ctx.lineWidth = 5; ctx.beginPath(); ctx.moveTo(p.x - nx * half, p.y - ny * half); ctx.lineTo(p.x + nx * half, p.y + ny * half); ctx.stroke(); ctx.shadowBlur = 0; ctx.fillStyle = '#f5fbff'; ctx.font = '700 10px Arial'; ctx.textAlign = 'center'; ctx.fillText(roulette < 1 ? 'LIGNE DE DÉPART · TIRAGE…' : 'LIGNE DE DÉPART', p.x + nx * (half + 19), p.y + ny * (half + 19)); ctx.restore(); }
      if (!live.current) { ctx.fillStyle = 'rgba(3,5,12,.48)'; ctx.fillRect(0, 0, w, h); ctx.fillStyle = '#f0f8ff'; ctx.font = '700 16px Arial'; ctx.fillText('PAUSE', w / 2, h / 2); }
      if (Math.floor(now / 120) !== Math.floor((now - 16) / 120)) setPhase(t < .72 ? 'Premier joueur : choix du point A' : t < 1.65 ? 'Second joueur : point B et séparation des deux moitiés' : base < 1 ? 'Deux gestes humains : courbes et vitesses différentes' : 'Boucle validée : génération du circuit et tirage de la ligne de départ');
      return;
    }
    const y = h * .47; const half = Math.min(96, h * .22); const x0 = w * .07; const x1 = w * .93; const wallX = w * .59; const deform = scenario === 'deform' ? Math.sin(clamp((t - 1.1) / .8, 0, 1) * Math.PI / 2) * half * 1.65 : 0; const lineY = (x: number) => scenario === 'deform' && x > wallX - w * .12 && x < wallX + w * .13 ? y - deform * Math.sin((x - wallX + w * .12) / (w * .25) * Math.PI) : y;
    const top: Point[] = []; const bottom: Point[] = []; for (let i = 0; i <= 80; i++) { const x = lerp(x0, x1, i / 80); top.push({ x, y: lineY(x) - half }); bottom.unshift({ x, y: lineY(x) + half }); }
    ctx.save(); ctx.shadowColor = '#22dffc'; ctx.shadowBlur = 28; ctx.fillStyle = '#07152d'; ctx.beginPath(); [...top, ...bottom].forEach((p, i) => i ? ctx.lineTo(p.x, p.y) : ctx.moveTo(p.x, p.y)); ctx.closePath(); ctx.fill(); ctx.restore(); ctx.save(); ctx.lineWidth = 4; ctx.shadowBlur = 16; ctx.shadowColor = '#39ecff'; ctx.strokeStyle = '#37dff5'; ctx.beginPath(); top.forEach((p, i) => i ? ctx.lineTo(p.x, p.y) : ctx.moveTo(p.x, p.y)); ctx.stroke(); ctx.shadowColor = '#ff5ede'; ctx.strokeStyle = '#fa58da'; ctx.beginPath(); bottom.slice().reverse().forEach((p, i) => i ? ctx.lineTo(p.x, p.y) : ctx.moveTo(p.x, p.y)); ctx.stroke(); ctx.setLineDash([12, 14]); ctx.shadowBlur = 0; ctx.lineWidth = 1.2; ctx.strokeStyle = 'rgba(226,245,255,.55)'; ctx.beginPath(); for (let i = 0; i <= 80; i++) { const x = lerp(x0, x1, i / 80); i ? ctx.lineTo(x, lineY(x)) : ctx.moveTo(x, lineY(x)); } ctx.stroke(); ctx.restore();
    const wall = scenario !== 'boost' && scenario !== 'slingshot'; if (wall) { ctx.save(); ctx.translate(wallX, y); ctx.rotate(scenario === 'respawn' ? -.62 : 0); ctx.shadowColor = '#ff426d'; ctx.shadowBlur = 23; ctx.fillStyle = '#f52f62'; ctx.fillRect(-10, -half * .93, 20, half * 1.86); ctx.fillStyle = '#ffe8f1'; ctx.fillRect(-3, -half * .83, 6, half * 1.66); ctx.restore(); }
    if (scenario === 'boost') { const v = [{ x: w * .43 - 54, y: y + half * .6 }, { x: w * .43 + 54, y }, { x: w * .43 - 54, y: y - half * .6 }]; ctx.save(); ctx.fillStyle = 'rgba(162,112,255,.25)'; ctx.strokeStyle = '#b891ff'; ctx.shadowColor = '#b891ff'; ctx.shadowBlur = 20; ctx.lineWidth = 4; ctx.beginPath(); v.forEach((p, i) => i ? ctx.lineTo(p.x, p.y) : ctx.moveTo(p.x, p.y)); ctx.closePath(); ctx.fill(); ctx.stroke(); ctx.restore(); if (t < 2.2) v.forEach((p, i) => touch(ctx, p, '#c6a5ff', now, `doigt ${i + 1}`)); }
    let progress = clamp((t - 1.4) / 6.3, 0, 1); if (scenario === 'boost') progress = t < 2.8 ? clamp((t - .5) / 2.3, 0, 1) * .42 : clamp(.42 + (t - 2.8) / 1.75 * .58, 0, 1); let cx = lerp(x0 + 25, x1 - 18, progress); let cy = lineY(cx); let rot = 0; let ghost = scenario === 'ghost' && t > 2.8 && t < 5.7; let falling = false; let hit = false;
    if (scenario === 'respawn') { if (t < 4) { cx = lerp(x0 + 25, wallX - 27, clamp((t - 1.1) / 2.9, 0, 1)); cy = y; } else if (t < 5.2) { falling = true; cx = wallX - 27 + (t - 4) * 110; cy = y + (t - 4) * 145; rot = (t - 4) * 4; } else if (t < 6.4) { cx = wallX + 105; cy = y + 174; } else { const u = clamp((t - 6.4) / 3.5, 0, 1); cx = lerp(wallX + 28, x1 - 25, u * u); cy = y; } }
    if (scenario === 'deform' && t > .75 && t < 2.8) { const d = clamp((t - .75) / 1.2, 0, 1); const leftStart = { x: wallX - w * .09, y: y - half + 15 }; const rightStart = { x: wallX + w * .09, y: y - half + 15 }; const left = { x: leftStart.x - d * 28, y: leftStart.y - d * half * 1.35 }; const right = { x: rightStart.x + d * 28, y: rightStart.y - d * half * 1.35 }; touch(ctx, left, '#76ffb4', now, 'saisir'); touch(ctx, right, '#76ffb4', now, 'étirer'); ctx.save(); ctx.strokeStyle = '#76ffb4'; ctx.setLineDash([5, 5]); ctx.lineWidth = 2; ctx.beginPath(); ctx.moveTo(leftStart.x, leftStart.y); ctx.lineTo(left.x, left.y); ctx.moveTo(rightStart.x, rightStart.y); ctx.lineTo(right.x, right.y); ctx.stroke(); ctx.restore(); }
    if (scenario === 'slingshot') { cx = lerp(x0 + 50, x1 - 60, clamp((t - 1.25) / 7, 0, 1)); cy = y; hit = t > 3.25 && t < 4.5; if (t > 1.1 && t < 2.7) { const a = { x: w * .27, y: h * .67 }; const c = { x: w * .37, y: h * .67 }; const pullProgress = clamp((t - 1.1) / 1.15, 0, 1); const pull = { x: lerp(w * .32, w * .23, pullProgress), y: lerp(h * .67, h * .81, pullProgress) }; touch(ctx, a, '#ff9c5b', now, 'appui 1'); touch(ctx, c, '#ff9c5b', now, 'appui 2'); touch(ctx, pull, '#ff9c5b', now, 'drag arrière'); ctx.save(); ctx.strokeStyle = '#ff9c5b'; ctx.shadowColor = '#ff9c5b'; ctx.shadowBlur = 18; ctx.lineWidth = 3; ctx.beginPath(); ctx.moveTo(a.x, a.y); ctx.lineTo(pull.x, pull.y); ctx.lineTo(c.x, c.y); ctx.stroke(); ctx.restore(); } if (t > 2.75 && t < 3.65) { const p = clamp((t - 2.75) / .9, 0, 1); ctx.save(); ctx.fillStyle = '#ffebc5'; ctx.shadowColor = '#ffad62'; ctx.shadowBlur = 20; ctx.beginPath(); ctx.arc(lerp(w * .23, cx, p), lerp(h * .81, cy, p), 7, 0, Math.PI * 2); ctx.fill(); ctx.restore(); } }
    ctx.save(); ctx.translate(cx, cy); ctx.rotate(rot); ctx.scale(falling ? .75 : 1, falling ? .75 : 1); ctx.shadowColor = ghost ? '#c8adff' : hit ? '#ff6c9b' : '#54efff'; ctx.shadowBlur = ghost ? 32 : 18; ctx.globalAlpha = ghost ? .48 : 1; ctx.fillStyle = '#78f2ff'; ctx.beginPath(); ctx.moveTo(17, 0); ctx.lineTo(-9, -8); ctx.lineTo(-13, 0); ctx.lineTo(-9, 8); ctx.closePath(); ctx.fill(); ctx.fillStyle = '#eaffff'; ctx.fillRect(-5, -3, 10, 6); ctx.restore(); const label = falling ? 'HORS PISTE' : scenario === 'respawn' && t > 6.4 && t < 7.8 ? 'RESPAWN · ACCÉLÉRATION' : hit ? '− 48 HP' : ghost ? 'FANTÔME' : scenario === 'boost' && t > 2.7 && t < 4.8 ? 'BOOST × 1.8' : ''; if (label) { ctx.fillStyle = falling || hit ? '#ff759b' : '#d4c1ff'; ctx.font = '700 12px Arial'; ctx.textAlign = 'center'; ctx.fillText(label, cx, cy - 25); }
    if (!live.current) { ctx.fillStyle = 'rgba(3,5,12,.48)'; ctx.fillRect(0, 0, w, h); ctx.fillStyle = '#f0f8ff'; ctx.font = '700 16px Arial'; ctx.textAlign = 'center'; ctx.fillText('PAUSE', w / 2, h / 2); }
    const message = scenario === 'deform' ? (t < 1.1 ? 'Coéquipier : saisie de la bordure' : t < 3 ? 'Déformation locale : voie dégagée' : 'La voiture contourne le mur') : scenario === 'ghost' ? (t < 2 ? 'Bonus chargé par le pilote' : t < 5.7 ? 'Pilote : mode fantôme maintenu' : 'Le mur est traversé sans impact') : scenario === 'boost' ? (t < 2.2 ? 'Coéquipier : trois doigts dessinent le boost' : t < 4.8 ? 'La voiture accélère dans la zone' : 'Sortie de la zone de boost') : scenario === 'slingshot' ? (t < 2.7 ? 'Coéquipier : deux appuis + drag vers l’arrière' : t < 3.7 ? 'Projectile guidé vers la voiture' : 'Impact : dégâts sur la voiture') : (t < 4 ? 'Mur orienté : trajectoire déviée' : t < 5.2 ? 'Sortie de piste' : t < 6.4 ? 'Pilote et coéquipier synchronisent le respawn' : 'Respawn après le mur : vitesse progressive'); if (Math.floor(now / 120) !== Math.floor((now - 16) / 120)) { setPhase(message); setHp(scenario === 'slingshot' && t > 3.25 ? 52 : 100); }
  }, [scenario]);
  useEffect(() => { const loop = (now: number) => { draw(now); frame.current = requestAnimationFrame(loop); }; frame.current = requestAnimationFrame(loop); return () => cancelAnimationFrame(frame.current); }, [draw]);
  useEffect(() => { const key = (event: KeyboardEvent) => { if (event.key === 'Escape' && screenshotRef.current) closeMock(); if (!mockLabRef.current) return; const mock = mockRef.current; const selected = selectedMockRef.current; if (event.key === 'a') { if (selected === 'wall' && mock.wall) mock.wall.angle -= Math.PI / 18; if (selected === 'carA' && mock.carA) mock.carA.angle -= Math.PI / 18; if (selected === 'carB' && mock.carB) mock.carB.angle -= Math.PI / 18; } if (event.key === 'e') { if (selected === 'wall' && mock.wall) mock.wall.angle += Math.PI / 18; if (selected === 'carA' && mock.carA) mock.carA.angle += Math.PI / 18; if (selected === 'carB' && mock.carB) mock.carB.angle += Math.PI / 18; } const delta = event.key === 'ArrowLeft' ? { x: -8, y: 0 } : event.key === 'ArrowRight' ? { x: 8, y: 0 } : event.key === 'ArrowUp' ? { x: 0, y: -8 } : event.key === 'ArrowDown' ? { x: 0, y: 8 } : null; if (!delta || !selected) return; const move = (p: Point | undefined) => p && { x: p.x + delta.x, y: p.y + delta.y }; if (selected === 'carA' && mock.carA) mock.carA.point = move(mock.carA.point)!; if (selected === 'carB' && mock.carB) mock.carB.point = move(mock.carB.point)!; if (selected === 'wall' && mock.wall) mock.wall.point = move(mock.wall.point)!; if (selected === 'pylon1') mock.pylon1 = move(mock.pylon1); if (selected === 'pylon2') mock.pylon2 = move(mock.pylon2); }; window.addEventListener('keydown', key); return () => window.removeEventListener('keydown', key); });
  const current = entries.find((item) => item.id === scenario)!;
  const syncPulse = scenario === 'respawn' && phase.includes('synchronisent'); const ghostPulse = scenario === 'ghost' && phase.includes('activation');
  const mockHint = mockTool === 'select' ? 'Sélectionner · glisser ou flèches · A / E tourner' : mockTool === 'draw' ? 'Tracer le circuit · cliquez-glissez' : mockTool === 'wall' ? 'Placer un mur · sélectionner pour tourner' : mockTool === 'pylon1' ? 'Placer le pilier 1' : mockTool === 'pylon2' ? 'Placer le pilier 2 · rapprocher pour relier' : 'Cliquer sur le circuit pour placer';
  if (screenshot) return <main className="mock-screen"><canvas ref={canvas} className="track" aria-label="Table de jeu en pause" /><div className="corner-post pilot-post tl"><div className="mock-wheel"><i /><b>◉</b></div><button>✦</button></div><div className="corner-post mate-post tr"><button>◇</button><button>⌁</button></div><div className="corner-post mate-post bl"><button>◇</button><button>⌁</button></div><div className="corner-post pilot-post br"><div className="mock-wheel"><i /><b>◉</b></div><button>✦</button></div></main>;
  if (mockLab) return <main className="demo"><canvas ref={canvas} className="track" onPointerDown={mockDown} onPointerMove={mockMove} onPointerUp={mockUp} onPointerLeave={mockUp} aria-label="Éditeur de table" /><header className="topbar"><div><strong>CRASHOUT · LAB</strong><span>MAQUETTE DE TABLE</span></div><div className="controls mock-lab-controls"><button onClick={showScreenshot}>▣</button><button onClick={() => { mockLabRef.current = false; setMockLab(false); }}>←</button></div></header><div className="mock-lab-hint">{mockHint}</div><aside className="mock-lab-tools"><button className={mockTool === 'select' ? 'selected' : ''} onClick={() => setMockTool('select')}>⌖</button><button className={mockTool === 'draw' ? 'selected' : ''} onClick={() => setMockTool('draw')}>⌁</button><button className={mockTool === 'carA' ? 'selected cyan' : ''} onClick={() => setMockTool('carA')}>▶</button><button className={mockTool === 'carB' ? 'selected pink' : ''} onClick={() => setMockTool('carB')}>▶</button><button className={mockTool === 'wall' ? 'selected red' : ''} onClick={() => setMockTool('wall')}>▮</button><button className={mockTool === 'pylon1' ? 'selected gold' : ''} onClick={() => setMockTool('pylon1')}>ϟ¹</button><button className={mockTool === 'pylon2' ? 'selected gold' : ''} onClick={() => setMockTool('pylon2')}>ϟ²</button><button onClick={() => { mockRef.current.track = []; mockRef.current.seeded = true; }}>⌫</button><button onClick={() => { const m = mockRef.current; const s = selectedMockRef.current; if (s === 'carA') m.carA = undefined; if (s === 'carB') m.carB = undefined; if (s === 'wall') m.wall = undefined; if (s === 'pylon1') m.pylon1 = undefined; if (s === 'pylon2') m.pylon2 = undefined; selectMock(null); }}>×</button></aside></main>;
  return <main className="demo"><canvas ref={canvas} className="track" aria-label="Simulation du scénario d’interaction" /><header className="topbar"><div><strong>CRASHOUT · INTERACTION LAB</strong><span>scènes de démonstration pour table multitouch</span></div><div className="live"><i className={running ? 'on' : ''} /> {running ? 'ANIMATION' : 'PAUSE'}</div></header><section className="scene-copy"><span>SCÈNE {entries.findIndex((item) => item.id === scenario) + 1} / {entries.length}</span><h1>{current.label}</h1><p>{phase}</p></section><div className="controls"><button onClick={toggle}>{running ? 'Ⅱ Pause' : '▶ Reprendre'}</button><button onClick={() => restart(scenario)}>↻ Rejouer</button><button onClick={openMock}>▣</button></div><section className="interaction-strip"><div className={`station-panel teammate ${['draw','deform','boost','slingshot','respawn'].includes(scenario) ? 'active' : ''}`}><div className="station-label"><small>POSTE COÉQUIPIER</small><span>TABLE / ACTION</span></div><div className="station-hardware"><div className={`repair-zone ${syncPulse ? 'tap' : ''}`}><i />SYNC<br /><b>RÉPARER</b></div><div className="tangible-dock"><i>◇</i><i>◇</i><span>RECHARGE</span></div></div><strong>{scenario === 'draw' ? 'Tracer sa moitié depuis le point A' : scenario === 'deform' ? 'Saisir / étirer une bordure' : scenario === 'boost' ? '3 doigts = polygone boost' : scenario === 'slingshot' ? '2 appuis + drag = lance-pierre' : scenario === 'respawn' ? 'Synchroniser le respawn' : 'Action disponible sur la table'}</strong></div><div className="scenario-picker">{entries.map((item) => <button key={item.id} className={scenario === item.id ? 'selected' : ''} onClick={() => restart(item.id)}><span>{item.label}</span><small>{item.detail}</small></button>)}</div><div className={`station-panel driver ${['draw','ghost','respawn'].includes(scenario) ? 'active' : ''}`}><div className="station-label"><small>POSTE PILOTE</small><span>CONDUITE / BONUS</span></div><div className="station-hardware"><div className="wheel"><i /><b>◉</b></div><div className={`bonus-zone ${ghostPulse ? 'tap' : ''}`}>✦<small>FANTÔME</small></div><div className={`repair-zone ${syncPulse ? 'tap' : ''}`}><i />SYNC</div></div><strong>{scenario === 'draw' ? 'Tracer sa moitié depuis le point B' : scenario === 'ghost' ? 'Activer : mode fantôme' : scenario === 'boost' ? 'Vitesse : BOOST × 1.8' : scenario === 'slingshot' ? `Intégrité : ${hp} HP` : scenario === 'respawn' ? 'Appui synchronisé : respawn' : 'Conduite : trajectoire libre'}</strong></div></section></main>;
}
